basic_settings:
  site_title: Zvi Biener
  site_tagline: 
  favicon_image: /images/favicon.png
  rss: '/feed.xml'

header_settings:
  logo_image: 
  logo_width: 200
  overlay_opacity: 0.7
  portfolio_overlay_opacity: 0.4

menu_settings:
  menu_items:
    - title: 'Research'
      url: '/projects/'
    - title: 'Publications'
      url: '/publications/'
    - title: 'Teaching'
      url: '/teaching/'
    - title: 'Tech'
      url: '/blog/'
    - title: 'CV'
      url: '/cv/'

grid_settings:
  grid_spacing: 10

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: 'https://github.com/zbiener'
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''


color_settings:
  background_color: '#fcfbf8'
  background_alt_color: '#e0e4e7'
  text_dark_color: '#2A2F36'
  text_medium_color: '#474747'
  text_light_color: '#fcfbf8'
  accent_color: '#474747'
  border_color: '#dddddd'
  overlay_background_color: '#161B21'
  overlay_text_color: '#ffffff'
  error_color: '#D64541'
  link_color: '#1562bd'

column_size:
#in percent
  tablelt: 95
  laptop: 92
  desktop: 90

font_settings:
# Only use google fonts
  title_font: 'Bree Serif'
  title_font_family: 'serif'
  body_font: 'Raleway'
  body_font_family: 'sans-serif'
  regular_weight: 400
  bold_weight: 700
  site_title:
    small_size: 34
    medium_size: 38
    large_size: 44
    weight: 400
    letter_spacing: 0
  site_tagline:
    small_size: 16
    medium_size: 17
    large_size: 18
    weight: 400
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 28
    medium_size: 24
    large_size: 24
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 26
    medium_size: 20
    large_size: 36
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    verysmall_size: 21
    small_size: 23
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 12
    medium_size: 14
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 14
    medium_size: 15
    large_size: 16
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 16
    medium_size: 16
    large_size: 16
    weight: 400
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 600
    letter_spacing: 0


advanced_settings:
  ajax_loading: false
  analytics_code: |
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-56661953-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-56661953-1');
    </script>
  custom_styles: ""
  header_js: ""
  footer_js: 